# Site settings
name: 杜俊峰
location: 四川成都
company: IBM
position: Java开发工程师
github: https://github.com/athc
facebook: https://www.facebook.com/dujf
phone: 15182719913
email: dujf54732@gmail.com

baseurl: "/index.html"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

